version: '3'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      - POSTGRES_USER=ubuntu
      - POSTGRES_PASSWORD=mlops
      - POSTGRES_DB=nba_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nba-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ubuntu -d nba_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_NAME=nba_db
      - DB_USER=ubuntu
      - DB_PASSWORD=mlops
    networks:
      - nba-network

networks:
  nba-network:
    driver: bridge

volumes:
  postgres_data: