version: '3.8'

services:
  data_ingestion:
    build:
      context: ..
      dockerfile: docker/Dockerfile.data_ingestion
    image: mihrando/data_ingestion:latest
    volumes:
      - ..:/app
      - ../logs:/app/logs
    depends_on: []
    environment:
      - WAIT_FOR_FILE=/app/signal_data_ingestion_done
      - WAIT_FOR_PREV_FILE=

  data_processing:
    build:
      context: ..
      dockerfile: docker/Dockerfile.data_processing
    image: mihrando/data_processing:latest
    volumes:
      - ..:/app
      - ../logs:/app/logs
    depends_on:
      - data_ingestion
    environment:
      - WAIT_FOR_FILE=/app/signal_data_processing_done
      - WAIT_FOR_PREV_FILE=/app/signal_data_ingestion_done

  feature_engineering:
    build:
      context: ..
      dockerfile: docker/Dockerfile.feature_engineering
    image: mihrando/feature_engineering:latest
    volumes:
      - ..:/app
      - ../logs:/app/logs
    depends_on:
      - data_processing
    environment:
      - WAIT_FOR_FILE=/app/signal_feature_engineering_done
      - WAIT_FOR_PREV_FILE=/app/signal_data_processing_done

  model_training:
    build:
      context: ..
      dockerfile: docker/Dockerfile.model_training
    image: mihrando/model_training:latest
    volumes:
      - ..:/app
      - ../logs:/app/logs
    depends_on:
      - feature_engineering
    environment:
      - WAIT_FOR_FILE=/app/signal_model_training_done
      - WAIT_FOR_PREV_FILE=/app/signal_feature_engineering_done
      - LOG_TO_MLFLOW=false  # Disable MLFlow logging in Docker Compose
      - MLFLOW_TRACKING_USERNAME=mihrandovlatyan
      - MLFLOW_TRACKING_PASSWORD=96e4b203f8905586136bc84272ba497374583499

  inference:
    build:
      context: ..
      dockerfile: docker/Dockerfile.inference
    image: mihrando/inference:latest
    volumes:    
      - ..:/app
      - ../logs:/app/logs
    depends_on:
      - model_training
    environment:
      - WAIT_FOR_FILE=/app/signal_inference_done
      - WAIT_FOR_PREV_FILE=/app/signal_model_training_done
