name: Generate New Data

on:
  push:
    branches:
      - retrain-the-model
  # Uncomment if you want to schedule the workflow to run at specific times
  #schedule:
  #  - cron: '0 9 * * 0' # Every Sunday at 09:00 UTC
  #  - cron: '50 7 * * 2'

permissions:
  contents: write  # Grant write permission to contents

jobs:
  generate_data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas scikit-learn joblib

    - name: Generate new_data.csv
      run: python generate_new_data.py

    - name: Commit and push new_data.csv
      run: |
        git config --global user.name "Github Action"
        git config --global user.email mihrandovlatyan@gmail.com
        git add "data/new_data/new_data.csv"
        git commit -m 'Add simulated new_data.csv for retraining'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_REPO_TOKEN }}
