name: Generate New Data

on:
  push:
    branches:
      - retrain-the-model
      - main
  # Uncomment if you want to schedule the workflow to run at specific times
  schedule:
    - cron: '0 9 * * 0' # Every Sunday at 09:00 UTC
  #  - cron: '50 7 * * 2'

permissions:
  contents: write  # Grant write permission to contents

jobs:
  generate_data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas scikit-learn joblib

    - name: Generate new_data.csv
      run: python generate_new_data.py

    - name: Commit and push new_data.csv
      run: python commit_and_push.py
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_REPO_TOKEN }}
