name: Generate New Data

on:
  schedule:
    - cron: '0 4 * * *' # Every day at 4 am at UTC
  #push:
  #  branches:
  #    - mlflow

permissions:
  contents: write  # Grant write permission to contents
 
jobs:
  generate_data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas scikit-learn joblib

    - name: Generate new_data.csv
      run: python generate_new_data.py

    - name: Commit and push new_data.csv
      run: |
        git config --global user.name "Mihran Dovlatyan"
        git config --global user.email mihrandovlatyan@gmail.com
        git add "data/new_data/new_data.csv"
        git pull
        git commit -m 'Add simulated new_data.csv for retraining'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_REPO_TOKEN }}
