# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python API Tests

on:
  push:
    branches:
      - main
      - training-pipeline
  pull_request:
    branches:
      - main
      - training-pipeline

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to use Node.js 20

      - name: Set up Python
        uses: actions/setup-python@v5  # Updated to use Node.js 20 and Python 3.12
        with:
          python-version: '3.9'  # Specify the Python version you need

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run tests
        env:
          PYTHONPATH: ./code  # $ export PYTHONPATH=./code
        run: |
          source venv/bin/activate  # Ensure virtual environment is activated
          pytest -v code/tests
