# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python API Tests

on:
  push:
    branches:
      - main
      - unit-tests
      - database_integration
  pull_request:
    branches:
      - main
      - unit-tests
      - database_integration

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    env:
      PYTHONPATH: ./code
      DB_HOST: localhost
      DB_NAME: nba_db
      DB_USER: ubuntu
      DB_PASSWORD: mlops

    services:
      postgres:
        image: postgres:12  # Use the desired PostgreSQL version
        env:
          POSTGRES_USER: ubuntu
          POSTGRES_PASSWORD: mlops
          POSTGRES_DB: nba_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to use Node.js 20

      - name: Set up Python
        uses: actions/setup-python@v5  # Updated to use Node.js 20 and Python 3.12
        with:
          python-version: '3.9'  # Specify the Python version you need

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Set up database
        run: |
          source venv/bin/activate
          python code/retrieve_data/setup_database.py
      
      - name: Run tests
        run: |
          source venv/bin/activate
          pytest -v code/tests

